<?php

namespace App\Providers;

use App\Category;
use App\User;
use Auth;
use Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        'App\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();
        Auth::login(User::find(1));
        //
    }

    public function registerPolicies()
    {
        Gate::define('has-category', function($user, Category $category) {
            return $category->user_id == $user->id;
        });
        parent::registerPolicies(); // TODO: Change the autogenerated stub
    }
}
